#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# 백서반영표 자동 로그 생성기
# 커밋 메시지의 "WP-Log:" 트레일러를 스캔해 src/data/wpAutoLog.js 를 생성한다.
# 형식(한 줄):  WP-Log: ch=8; ver=v1.2; feat=기능명; src=섹션경로; summary=반영 요약
#   - ch: 챕터 번호(콤마로 다중, 예 ch=7,8). 없으면 생략 가능.
#   - ver: 백서 버전(생략 시 v1.1)
#   - feat/src/summary: 텍스트(summary 는 마지막에 두고 ; 를 쓰지 말 것)
# 빌드(build_preview.sh)와 git post-commit 훅에서 자동 호출된다.
# ─────────────────────────────────────────────────────────────
set -e
cd "$(dirname "$0")/.."
OUT="src/data/wpAutoLog.js"

# git 이 없거나 저장소가 아니면(예: Vercel 정적 서빙) 기존 파일 유지 / 빈 배열 보장
if ! command -v git >/dev/null 2>&1 || ! git rev-parse --git-dir >/dev/null 2>&1; then
  [ -f "$OUT" ] || printf '/* auto */\nconst WP_AUTO_LOG = [];\n' > "$OUT"
  exit 0
fi

esc(){ printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
field(){ printf '%s' "$2" | grep -oiP "(?<=$1=)[^;]*" | head -1 | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
sumfield(){ printf '%s' "$1" | grep -oiP '(?<=summary=).*' | head -1 | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }

rows=""
n=0
while IFS=$'\x1f' read -r -d $'\x1e' hash date bodz; do
  hash=${hash//[$'\n\r\t ']/}
  date=${date//[$'\n\r\t']/}
  line=$(printf '%s' "$bodz" | grep -m1 -i '^WP-Log:' || true)
  [ -z "$line" ] && continue
  payload=${line#*:}
  ch=$(field ch "$payload")
  ver=$(field ver "$payload"); [ -z "$ver" ] && ver="v1.1"
  feat=$(field feat "$payload")
  src=$(field src "$payload")
  summary=$(sumfield "$payload")
  chArr=$(printf '%s' "$ch" | awk -F, '{o="";for(i=1;i<=NF;i++){g=$i;gsub(/[^0-9]/,"",g);if(g!="")o=o (o==""?"":",") g}print o}')
  rows+="  { date:\"$date\", ver:\"$(esc "$ver")\", ch:[$chArr], feat:\"$(esc "$feat")\", src:\"$(esc "$src")\", summary:\"$(esc "$summary")\", refs:[], status:\"반영\", hash:\"$hash\", auto:true },"$'\n'
  n=$((n+1))
done < <(git log --no-merges --date=short --pretty=format:'%h%x1f%ad%x1f%B%x1e')

{
  printf '/* AUTO-GENERATED by scripts/gen_wp_log.sh — 직접 편집 금지.\n'
  printf '   커밋 메시지의 "WP-Log:" 트레일러에서 빌드/커밋 시 자동 생성됩니다. */\n'
  printf 'const WP_AUTO_LOG = [\n'
  printf '%s' "$rows"
  printf '];\n'
} > "$OUT"
echo "gen_wp_log: $n auto entries -> $OUT"
